# permissions for end users to edit consulkvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: consulkv-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: consulkv-commander
    app.kubernetes.io/part-of: consulkv-commander
    app.kubernetes.io/managed-by: kustomize
  name: consulkv-editor-role
rules:
- apiGroups:
  - sas.com.sas.com
  resources:
  - consulkvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sas.com.sas.com
  resources:
  - consulkvs/status
  verbs:
  - get
